### ISSUE TITLE
Getting error for LSTM training

### ISSUE THREAD

**Issue by rish27** [yuewang-cuhk/HashtagGeneration#1]
https://github.com/yuewang-cuhk/HashtagGeneration/blob/9d281db8d60918687f517ce8ff73b968e64e8486/onmt/Models.py#L321

When configured on train using LSTM's getting below error:
Traceback (most recent call last):
  File "../train.py", line 516, in <module>
    main()
  File "../train.py", line 508, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "../train.py", line 262, in train_model
    train_stats = trainer.train(train_iter, epoch, opt.max_src_len, opt.max_conv_len, report_func)
  File "/content/drive/My Drive/Colab Notebooks/IREProject/HashtagGeneration/onmt/Trainer.py", line 183, in train
    max_src_len, max_conv_len)
  File "/content/drive/My Drive/Colab Notebooks/IREProject/HashtagGeneration/onmt/Trainer.py", line 333, in _gradient_accumulation
    max_src_len, max_conv_len, dec_state)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Colab Notebooks/IREProject/HashtagGeneration/onmt/Models.py", line 760, in forward
    enc_final, memory_bank = self.encoder(src, conversation, lengths)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Colab Notebooks/IREProject/HashtagGeneration/onmt/Models.py", line 322, in forward
    hidden = self.combine_hidden(torch.cat([src_hidden, ans_hidden], dim=-1))  # [2, batch_size, hidden]
TypeError: expected Tensor as element 0 in argument 0, but got tuple
TypeError: expected Tensor as element 0 in argument 0, but got tuple

**Comment by yuewang-cuhk** [comment]
Hi, I have not tested the LSTM cell yet as I adopt GRU cell for this project. So you should be careful when using LSTM cell (GRU is highly recommended). From this error prompts, we can see that the errors come from the different outputs of LSTM cell compared to GRU. For LSTM cell, it outputs a tuple of [(hidden state h_n, cell state c_n)](https://pytorch.org/docs/stable/nn.html). You need to convert this tuple into a Tensor and be careful about the dimension size when initialing decoder state (see `self._bridge`)
